name: start_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ui
  circle_nav_bar: ^2.0.1+1
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  another_flushbar: ^1.12.30
  flutter_svg: ^2.0.9
  otp_text_field: ^1.1.3
  flutter_native_splash: ^2.3.5
  modal_progress_hud_nsn: ^0.5.1
  image_picker: ^1.0.4
  qr_code_scanner: ^1.0.1
  lottie: ^2.7.0
  webview_flutter: ^4.4.2

  # State Management
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  meta: ^1.9.1
  equatable: ^2.0.5

  # Localization
  flutter_localizations:
    sdk: flutter

  # Responsive
  flutter_screenutil: ^5.9.0

  # Service Locator
  get_it: ^7.6.4

  # Network
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  internet_connection_checker: ^1.0.0+1

  # Local Database
  shared_preferences: ^2.2.1
  cached_network_image: ^3.3.0
  hydrated_bloc: ^9.1.3
  path_provider: ^2.1.2

  # Others

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/jsons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets\fonts\Roboto\Roboto-Light.ttf
          weight: 300
        - asset: assets\fonts\Roboto\Roboto-Regular.ttf
          weight: 400
        - asset: assets\fonts\Roboto\Roboto-Medium.ttf
          weight: 500
        - asset: assets\fonts\Roboto\Roboto-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  output_dir: lib/resources/localization/generated
  arb_dir: lib/resources/localization/l10n

flutter_native_splash:
  image: assets/images/logo.png
  color: "#ffffff"
  android: true
  ios: true

flutter_assets:
  assets_path: assets/
  output_path: lib/resources/constants/
  filename: app_assets.dart
  field_prefix:

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/logo_foreground.png"
#   adaptive_icon_backgorund: "#105161"
#   adaptive_icon_foreground: "assets/images/logo_foreground.png"
